const checkAttempt = require('../controllers/challengeActivity/checkAttempt')
const saveAttempt = require('../controllers/challengeActivity/submitChallengeAnswer')
const commentIssue = require('../controllers/issueActivity/commentIssue')
const starIssue = require('../controllers/issueActivity/starIssue')
const postMessage = require('../controllers/message/postMessage')
const readAllMessages = require('../controllers/message/readAllMessages')
const notifyUsers = require('../controllers/notification/notifyUsers')
const readAllNotifications = require('../controllers/notification/readAllNotifications')
const likeVideo = require('../controllers/videoActivity/likeVideo')
const commentVideo = require('../controllers/videoActivity/commentVideo')
const playlistVideo = require('../controllers/videoActivity/savePlaylist')
const authenticate = require('../middlewares/authenticate')
const updateActiveUsers = require('../controllers/userActivity/saveActivity')
const saveIssue = require('../controllers/issueActivity/saveIssue')
const searchIssue = require('../controllers/issueActivity/searchIssue')
const purchaseCourse = require('../controllers/userActivity/purchaseCourse')
const setGoal = require('../controllers/userActivity/setGoal')
const completedVideo = require('../controllers/videoActivity/completedVideo')
const createForChargeRequest = require('../controllers/userActivity/createCharge')
const updateGroupChat = require('../controllers/message/publicMessage')

const router = require('express').Router()


router.post('/user/active', authenticate, updateActiveUsers)
router.post('/issue/star', authenticate, starIssue)
router.post('/issue/comment', authenticate, commentIssue)
router.post('/issue/search', authenticate, searchIssue)
router.post('/issue/submit_issue', authenticate, saveIssue)
router.post('/challenge/check_attempt', authenticate, checkAttempt)
router.post('/challenge/submit_challenge_answer', authenticate, saveAttempt)
router.post('/notification/send', authenticate, notifyUsers)
router.post('/notifications/read_all', authenticate, readAllNotifications)
// router.post('/messages/read_all', authenticate, readAllMessages)
router.post('/message/post', authenticate, postMessage)
router.post('/message/public', authenticate, updateGroupChat)
router.post('/video/like', authenticate, likeVideo)
router.post('/video/comment', authenticate, commentVideo)
router.post('/video/complete', authenticate, completedVideo)
router.post('/video/playlist', authenticate, playlistVideo)
router.post('/course/purchase', authenticate, purchaseCourse)
router.post('/course/set_goal', authenticate, setGoal)
router.post('/course/create_for_charge_request', authenticate, createForChargeRequest)


module.exports = router